# Form implementation generated from reading ui file 'fifth.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(433, 340)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.widgetArt = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.widgetArt.setContentsMargins(0, 0, 0, 0)
        self.widgetArt.setObjectName("widgetArt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
