# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 454)
        self.timeEdit = QtWidgets.QTimeEdit(parent=Form)
        self.timeEdit.setGeometry(QtCore.QRect(0, 0, 311, 41))
        self.timeEdit.setObjectName("timeEdit")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 40, 311, 321))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 370, 311, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.addEventBtn = QtWidgets.QPushButton(parent=Form)
        self.addEventBtn.setGeometry(QtCore.QRect(0, 410, 311, 41))
        self.addEventBtn.setObjectName("addEventBtn")
        self.eventList = QtWidgets.QListWidget(parent=Form)
        self.eventList.setGeometry(QtCore.QRect(310, 0, 301, 451))
        self.eventList.setObjectName("eventList")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addEventBtn.setText(_translate("Form", "Добавить событие"))
